### ISSUE TITLE
Horizontal Pod Autoscaler與Deployment的resource.limits和resource.requests之間的關係

### ISSUE THREAD

**Issue by IvanaGyro** [popdaily/popdaily.blog#20]
Horizontal Pod Autoscaler(HPA)中所設定百分比門檻是從Deplyment.resources.requests計算出來，而不是limits。

以下方為例
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: popdaily-server
spec:
  template:
    spec:
      containers:
      - name: server
        image: gcr.io/popdaily-198306/popdaily.server-staging
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
...
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: popdaily-server
  namespace: default
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: popdaily-server
  targetCPUUtilizationPercentage: 80
```
當只有一個pod且其CPU使用率為`500m`時，HPA的狀態會顯示使用率為400% (`500/(125*80%)`)而非40%。
```bash
user@hostname:/$ kubectl get hpa
NAME              REFERENCE                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
popdaily-server   Deployment/popdaily-server   400%/80%    1         6         1          1m
```
等到HPA修改運行中的Deployment的Replicas數值後則會顯示為
```bash
user@hostname:/$ kubectl get hpa
NAME              REFERENCE                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
popdaily-server   Deployment/popdaily-server   80%/80%    1         6         5          1m
```
